kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: $K8S_NAMESPACE
  name: file-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem