kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: $K8S_NS_AI
  name: file-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: $PVC_SIZE
  storageClassName: rook-cephfs
  volumeMode: Filesystem
