// src/mockData.ts

export const mockApiResponse = {
  items: [
    {
      id: 170,
      name: 'pro_test_10',
      trainModelVersion: null,
      testModelVersion: null,
      deployModelVersion: null,
      trainJob: null,
      testJob: null,
      anotherTestJob: null,
      model: {
        id: 111,
        modelName: 'test_model',
        modelNickName: 'test_model_nick_name',
        mainConfig: null,
        monitorType: 0,
        description: 'test_model_desc',
        areaLabelingTip: null,
        isDelete: 0,
        modelStatus: 1,
        isBoundWithGeneration: 2,
        modelConfigList: [],
        subsystem: 'CENTRAL_PLATFORM',
        createTime: '2024-07-01 12:39:55',
        applyTime: '2024-08-28 18:15:19',
        creatorId: 1,
        applicantId: 1,
        releaseStatus: 1,
        dataType: null,
        trainModelVersion: {
          id: 69,
          name: 'trainimage_1.0',
          level: '1.0',
          versionLevel: 0,
          showName: 'trainimage',
          description: 'desc',
          size: 2048,
          modelConfigList: [
            {
              id: 397,
              field: 'HP_BATCH_SIZE',
              label: null,
              defaultNum: null,
              required: true,
              min: null,
              max: null,
              msg: 'numeric:[1,)',
            },
            {
              id: 398,
              field: 'HP_CONFIDENCE',
              label: null,
              defaultNum: null,
              required: true,
              min: null,
              max: null,
              msg: 'numeric:(0,1)',
            },
            {
              id: 399,
              field: 'HP_WEIGHT_DECAY',
              label: null,
              defaultNum: null,
              required: true,
              min: null,
              max: null,
              msg: 'numeric:(,)',
            },
            {
              id: 400,
              field: 'HP_EPOCHES',
              label: null,
              defaultNum: null,
              required: true,
              min: null,
              max: null,
              msg: 'numeric:[1,)',
            },
            {
              id: 401,
              field: 'HP_MOMENTUN',
              label: null,
              defaultNum: null,
              required: true,
              min: null,
              max: null,
              msg: 'numeric:(,)',
            },
            {
              id: 402,
              field: 'HP_LEARNING_RATE',
              label: null,
              defaultNum: null,
              required: true,
              min: null,
              max: null,
              msg: 'numeric:(,)',
            },
          ],
          architecture: 'arm64',
          weightPath: null,
          reuseId: 0,
          url: 'trainimage_image1719808736031',
          createTime: '2024-07-01 12:38:57',
          isDelete: 0,
          trainNum: null,
          inspectNum: null,
          areaLabelingTip: null,
          status: 1,
          conversionPlatform: null,
          roleId: 1,
          useGpu: true,
          inferable: false,
          inspectable: false,
          trainable: true,
          reuse: false,
          autoLabel: false,
        },
        deployModelVersion: null,
        convertModelVersion: {
          id: 66,
          name: 'convert0619_v1',
          level: 'v1',
          versionLevel: 0,
          showName: 'convert0619',
          description: 'convert',
          size: 2048,
          modelConfigList: [],
          architecture: 'arm64',
          weightPath: null,
          reuseId: 0,
          url: 'convert0619_image1718774009027',
          createTime: '2024-06-19 13:13:29',
          isDelete: 0,
          trainNum: null,
          inspectNum: null,
          areaLabelingTip: null,
          status: 1,
          conversionPlatform: null,
          roleId: 1,
          useGpu: false,
          inferable: false,
          inspectable: true,
          trainable: false,
          reuse: false,
          autoLabel: false,
        },
        bestWeightPath: 'job-cloud-merge-665',
        source: 1,
        rejectReason: null,
        autoLabelModelVersion: null,
        releaseJob: {
          id: 665,
          name: 'job-cloud-merge-665',
          modelVersion: null,
          jobType: 1,
          controller: null,
          status: 1,
          modelGenerationId: 168,
          description: null,
          params: {
            HP_BATCH_SIZE: '10',
            HP_CONFIDENCE: '0.85',
            HP_EPOCHES: '5',
            HP_WEIGHT_DECAY: '0.0005',
            HP_MOMENTUN: '0.937',
            HP_LEARNING_RATE: '0.01',
            MODEL_WORKING_MODE: '1',
          },
          weightPath: 'job-cloud-merge-665',
          memory: '10Gi',
          cpus: '4',
          gpus: '2',
          logFilePath: null,
          createTime: '2024-07-01 12:43:43',
          lastJobTime: '2024-07-01 12:45:00',
          accuracy: null,
        },
      },
      isRelease: null,
      isReuse: true,
      isGuided: false,
      trainDataset: {
        id: 227,
        datasetId: 179,
        dataType: 0,
        annotateType: 102,
        name: 'test0619sdajadj',
        versionName: 'V0001',
        versionSource: null,
        fullName: null,
        createTime: '2024-06-19T03:09:55.000+00:00',
        versionNote: '',
        isCurrent: true,
        status: 0,
        fileCount: null,
        progressVO: null,
        versionUrl: 'dataset/179/versionFile/V0001',
        versionOfRecordUrl: null,
        dataConversion: 1,
        imageCounts: null,
        presetFlag: null,
        isOfRecord: null,
        format: 'YOLO',
      },
      testDataset: null,
      valDataset: null,
      hasDeployments: null,
      datasetSource: 0,
      splitSize: null,
      createTime: '2024-07-01 12:55:58',
      status: 10,
      description: 'pro_test_10_desc',
      hardwareParams: {
        id: 4,
        name: '4核10G',
        memory: '10Gi',
        cpus: '4',
        gpus: '2',
      },
      delayTrainTime: 0,
      maxTrainTime: 0,
      userName: '系统管理员',
      latestJobId: 669,
      modelStore: null,
      canPublish: null,
      hyperParams: {
        HP_BATCH_SIZE: '10',
        HP_CONFIDENCE: '0.85',
        HP_EPOCHES: '5',
        HP_WEIGHT_DECAY: '0.0005',
        HP_MOMENTUN: '0.937',
        HP_LEARNING_RATE: '0.01',
        MODEL_WORKING_MODE: '1',
      },
    },
    {
      id: 156,
      name: 'pro_gudei_test_000001',
      trainModelVersion: null,
      testModelVersion: null,
      deployModelVersion: null,
      trainJob: null,
      testJob: null,
      anotherTestJob: null,
      model: {
        id: 108,
        modelName: '训练加模型转换',
        modelNickName: '模型转换',
        mainConfig: null,
        monitorType: 0,
        description: '模型转换desc',
        areaLabelingTip: null,
        isDelete: 0,
        modelStatus: 1,
        isBoundWithGeneration: 2,
        modelConfigList: [],
        subsystem: 'CENTRAL_PLATFORM',
        createTime: '2024-06-19 14:17:55',
        applyTime: '2024-06-22 21:26:20',
        creatorId: 1,
        applicantId: 1,
        releaseStatus: 2,
        dataType: null,
        trainModelVersion: {
          id: 63,
          name: 'cztest001_v1.0',
          level: 'v1.0',
          versionLevel: 0,
          showName: 'test001',
          description: 'desc',
          size: 2048,
          modelConfigList: [
            {
              id: 370,
              field: 'HP_BATCH_SIZE',
              label: null,
              defaultNum: null,
              required: true,
              min: null,
              max: null,
              msg: 'numeric:[1,)',
            },
            {
              id: 371,
              field: 'HP_CONFIDENCE',
              label: null,
              defaultNum: null,
              required: true,
              min: null,
              max: null,
              msg: 'numeric:(0,1)',
            },
            {
              id: 372,
              field: 'HP_WEIGHT_DECAY',
              label: null,
              defaultNum: null,
              required: true,
              min: null,
              max: null,
              msg: 'numeric:(,)',
            },
            {
              id: 373,
              field: 'HP_EPOCHES',
              label: null,
              defaultNum: null,
              required: true,
              min: null,
              max: null,
              msg: 'numeric:[1,)',
            },
            {
              id: 374,
              field: 'HP_MOMENTUN',
              label: null,
              defaultNum: null,
              required: true,
              min: null,
              max: null,
              msg: 'numeric:(,)',
            },
            {
              id: 375,
              field: 'HP_LEARNING_RATE',
              label: null,
              defaultNum: null,
              required: true,
              min: null,
              max: null,
              msg: 'numeric:(,)',
            },
          ],
          architecture: 'arm64',
          weightPath: null,
          reuseId: 0,
          url: 'cztest001_image1718767080397',
          createTime: '2024-06-19 11:18:01',
          isDelete: 0,
          trainNum: null,
          inspectNum: null,
          areaLabelingTip: null,
          status: 1,
          conversionPlatform: null,
          roleId: 1,
          inspectable: false,
          autoLabel: false,
          reuse: false,
          useGpu: true,
          trainable: true,
          inferable: false,
        },
        deployModelVersion: null,
        convertModelVersion: {
          id: 66,
          name: 'convert0619_v1',
          level: 'v1',
          versionLevel: 0,
          showName: 'convert0619',
          description: 'convert',
          size: 2048,
          modelConfigList: [],
          architecture: 'arm64',
          weightPath: null,
          reuseId: 0,
          url: 'convert0619_image1718774009027',
          createTime: '2024-06-19 13:13:29',
          isDelete: 0,
          trainNum: null,
          inspectNum: null,
          areaLabelingTip: null,
          status: 1,
          conversionPlatform: null,
          roleId: 1,
          inspectable: true,
          autoLabel: false,
          reuse: false,
          useGpu: false,
          trainable: false,
          inferable: false,
        },
        bestWeightPath: 'job-cloud-merge-607',
        source: 1,
        rejectReason: null,
        autoLabelModelVersion: null,
        releaseJob: {
          id: 607,
          name: 'job-cloud-merge-607',
          modelVersion: null,
          jobType: 1,
          controller: null,
          status: 1,
          modelGenerationId: 156,
          description: null,
          params: {
            HP_BATCH_SIZE: '10',
            HP_CONFIDENCE: '0.85',
            HP_EPOCHES: '10',
            HP_WEIGHT_DECAY: '0.0005',
            HP_MOMENTUN: '0.937',
            HP_LEARNING_RATE: '0.01',
            MODEL_WORKING_MODE: '1',
          },
          weightPath: 'job-cloud-merge-607',
          memory: '10Gi',
          cpus: '4',
          gpus: '2',
          logFilePath: null,
          createTime: '2024-06-19 14:19:33',
          lastJobTime: '2024-06-19 14:20:40',
          accuracy: null,
        },
      },
      isRelease: null,
      isReuse: true,
      isGuided: false,
      trainDataset: {
        id: 227,
        datasetId: 179,
        dataType: 0,
        annotateType: 102,
        name: 'test0619sdajadj',
        versionName: 'V0001',
        versionSource: null,
        fullName: null,
        createTime: '2024-06-19T03:09:55.000+00:00',
        versionNote: '',
        isCurrent: true,
        status: 0,
        fileCount: null,
        progressVO: null,
        versionUrl: 'dataset/179/versionFile/V0001',
        versionOfRecordUrl: null,
        dataConversion: 1,
        imageCounts: null,
        presetFlag: null,
        isOfRecord: null,
        format: 'YOLO',
      },
      testDataset: null,
      valDataset: null,
      hasDeployments: null,
      datasetSource: 0,
      splitSize: null,
      createTime: '2024-06-19 14:18:51',
      status: 14,
      description: 'pro_gudei_test_000001_desc',
      hardwareParams: {
        id: 4,
        name: '4核10G',
        memory: '10Gi',
        cpus: '4',
        gpus: '2',
      },
      delayTrainTime: 0,
      maxTrainTime: 0,
      userName: '系统管理员',
      latestJobId: 624,
      modelStore: null,
      canPublish: null,
      hyperParams: {
        HP_BATCH_SIZE: '10',
        HP_CONFIDENCE: '0.85',
        HP_EPOCHES: '10',
        HP_WEIGHT_DECAY: '0.0005',
        HP_MOMENTUN: '0.937',
        HP_LEARNING_RATE: '0.01',
        MODEL_WORKING_MODE: '1',
      },
    },
    {
      id: 154,
      name: 'pro_guide_test',
      trainModelVersion: null,
      testModelVersion: null,
      deployModelVersion: null,
      trainJob: null,
      testJob: null,
      anotherTestJob: null,
      model: {
        id: 107,
        modelName: '安全帽',
        modelNickName: '安全帽算法',
        mainConfig: null,
        monitorType: 0,
        description: '识别算法',
        areaLabelingTip: null,
        isDelete: 0,
        modelStatus: 1,
        isBoundWithGeneration: 2,
        modelConfigList: [],
        subsystem: 'CENTRAL_PLATFORM',
        createTime: '2024-06-19 12:32:28',
        applyTime: '2024-06-19 12:41:37',
        creatorId: 1,
        applicantId: 1,
        releaseStatus: 2,
        dataType: null,
        trainModelVersion: {
          id: 64,
          name: 'asda_v.10',
          level: 'v.10',
          versionLevel: 0,
          showName: 'asda',
          description: 'desc',
          size: 2048,
          modelConfigList: [
            {
              id: 376,
              field: 'HP_BATCH_SIZE',
              label: null,
              defaultNum: null,
              required: true,
              min: null,
              max: null,
              msg: 'numeric:[1,)',
            },
            {
              id: 377,
              field: 'HP_CONFIDENCE',
              label: null,
              defaultNum: null,
              required: true,
              min: null,
              max: null,
              msg: 'numeric:(0,1)',
            },
            {
              id: 378,
              field: 'HP_WEIGHT_DECAY',
              label: null,
              defaultNum: null,
              required: true,
              min: null,
              max: null,
              msg: 'numeric:(,)',
            },
            {
              id: 379,
              field: 'HP_EPOCHES',
              label: null,
              defaultNum: null,
              required: true,
              min: null,
              max: null,
              msg: 'numeric:[1,)',
            },
            {
              id: 380,
              field: 'HP_MOMENTUN',
              label: null,
              defaultNum: null,
              required: true,
              min: null,
              max: null,
              msg: 'numeric:(,)',
            },
            {
              id: 381,
              field: 'HP_LEARNING_RATE',
              label: null,
              defaultNum: null,
              required: true,
              min: null,
              max: null,
              msg: 'numeric:(,)',
            },
          ],
          architecture: 'arm64',
          weightPath: null,
          reuseId: 0,
          url: 'asda_image1718771427271',
          createTime: '2024-06-19 12:30:28',
          isDelete: 0,
          trainNum: null,
          inspectNum: null,
          areaLabelingTip: null,
          status: 1,
          conversionPlatform: null,
          roleId: 1,
          inspectable: false,
          autoLabel: false,
          reuse: false,
          useGpu: true,
          trainable: true,
          inferable: false,
        },
        deployModelVersion: null,
        convertModelVersion: null,
        bestWeightPath: 'job-cloud-merge-600',
        source: 1,
        rejectReason: null,
        autoLabelModelVersion: null,
        releaseJob: {
          id: 600,
          name: 'job-cloud-merge-600',
          modelVersion: null,
          jobType: 1,
          controller: null,
          status: 1,
          modelGenerationId: 154,
          description: null,
          params: {
            HP_BATCH_SIZE: '10',
            HP_CONFIDENCE: '0.85',
            HP_EPOCHES: '10',
            HP_WEIGHT_DECAY: '0.0005',
            HP_MOMENTUN: '0.937',
            HP_LEARNING_RATE: '0.01',
            MODEL_WORKING_MODE: '1',
          },
          weightPath: 'job-cloud-merge-600',
          memory: '10Gi',
          cpus: '4',
          gpus: null,
          logFilePath: null,
          createTime: '2024-06-19 12:37:37',
          lastJobTime: '2024-06-19 12:38:50',
          accuracy: null,
        },
      },
      isRelease: null,
      isReuse: true,
      isGuided: false,
      trainDataset: {
        id: 227,
        datasetId: 179,
        dataType: 0,
        annotateType: 102,
        name: 'test0619sdajadj',
        versionName: 'V0001',
        versionSource: null,
        fullName: null,
        createTime: '2024-06-19T03:09:55.000+00:00',
        versionNote: '',
        isCurrent: true,
        status: 0,
        fileCount: null,
        progressVO: null,
        versionUrl: 'dataset/179/versionFile/V0001',
        versionOfRecordUrl: null,
        dataConversion: 1,
        imageCounts: null,
        presetFlag: null,
        isOfRecord: null,
        format: 'YOLO',
      },
      testDataset: null,
      valDataset: null,
      hasDeployments: null,
      datasetSource: 0,
      splitSize: null,
      createTime: '2024-06-19 12:35:00',
      status: 6,
      description: 'pro_guide_test_desc',
      hardwareParams: {
        id: 4,
        name: '4核10G',
        memory: '10Gi',
        cpus: '4',
        gpus: '2',
      },
      delayTrainTime: 0,
      maxTrainTime: 0,
      userName: '系统管理员',
      latestJobId: 664,
      modelStore: null,
      canPublish: null,
      hyperParams: {
        HP_BATCH_SIZE: '10',
        HP_CONFIDENCE: '0.85',
        HP_EPOCHES: '10',
        HP_WEIGHT_DECAY: '0.0005',
        HP_MOMENTUN: '0.937',
        HP_LEARNING_RATE: '0.01',
        MODEL_WORKING_MODE: '1',
      },
    },
  ],
  pageable: {
    sort: {
      sorted: true,
      unsorted: false,
      empty: false,
    },
    pageNumber: 0,
    pageSize: 10,
    offset: 0,
    paged: true,
    unpaged: false,
  },
  last: false,
  totalPages: 2,
  total: 1,
  sort: {
    sorted: true,
    unsorted: false,
    empty: false,
  },
  first: true,
  numberOfElements: 10,
  size: 10,
  number: 0,
  empty: false,
};
